### ISSUE TITLE
EWAS: fixed vs random and multiple batch effects

### ISSUE THREAD

**Issue by royfrancis** [perishky/meffil#13]
So, when running `meffil.ewas()`, variable of interest (variable) is a vector, fixed effects (covariates) is a data.frame and random effects (batch) is a vector.

I am using Sex as covariate. I have multiple batch effects (Sample_Plate, Slide and Array), How would I include that? Should I just include them all as covariates then? What is practically the downstream consequence of including some variables as fixed and other as random?

**Comment by epzjlm** [comment]
I would include them as covariates. It is very likely that there might be collinearity between the batch effects which might result that the model can't fit. So you need to make sure that the covariates are independent of each other. Although it would be more correct to fit batch effects as a random effect, the results wouldn't differ much.
