### ISSUE TITLE
Version conflicts with CopyNumber450k

### ISSUE THREAD

**Issue by jakoberr** [perishky/meffil#15]
Hey,

I have trouble when trying to extract structural variants (as explained[ here](https://github.com/perishky/meffil/wiki/Extracting-structural-variants)).

Appearently the `CopyNumber450k` package which is used in your pipeline was removed with Bioconductor 3.5 (see https://www.bioconductor.org/checkResults/3.5/bioc-20171018/). 
Yet, all releases below 3.5 are not compatible with R >3.5.3 anymore. 
Additionally there are some dependencies of `meffil` which need R >3.5.3 to function properly.

This basically means, that there are some unadressed version conflicts and I currently don't know  how to fix them. I don't know if using multiple R versions on my device will fix these issues, since there would be the need of switching back and forth in the same session which is (afaik) not possible.

Do you have any ideas how to fix this? Or do you know any alternatives to the `CopyNumber450k` package which can be used with `meffil`? I'm not sure if I understood the role of the `CopyNumber450k` package in your script throughly, so maybe I'm missing an easy solution.

**Comment by perishky** [comment]
To compute copy number variation, you actually need CopyNumber450kData, not CopyNumber450k.  Unfortunately neither is available in the most recent version of Bioconductor.  One possible solution is to install the package from source.  I've added this to the instructions on the wiki page (https://github.com/perishky/meffil/wiki/Extracting-structural-variants). I'm trying it out now, it seems to have installed alright...

**Comment by perishky** [comment]
This solution works for me.  Let me know how it goes.

**Comment by jakoberr** [comment]
Hey, thank you for your fast reply and the solution which works :)

**Comment by perishky** [comment]
Excellent!
