### ISSUE TITLE
new cell type reference

### ISSUE THREAD

**Issue by jromanowska** [perishky/meffil#18]
The documentation says that one can create a new cell type reference by using 'meffil.create.cell.type.reference()' function, but in R I get an error (could not find function "meffil.create.cell.type.reference"). I saw in the code here, on github, that there is no such function, but instead two other similar functions: 'meffil.add.cell.type.reference' and 'create.cell.type.reference'. Why aren't those linked correctly? Which one should I use?

**Comment by perishky** [comment]
Sorry, that was a typo.  You should use meffil.add.cell.type.reference. I've just fixed the error, thank you!

**Comment by jromanowska** [comment]
Great! Thanks!
