### ISSUE TITLE
normalized control probe values

### ISSUE THREAD

**Issue by dorks81** [perishky/meffil#25]
Hi,

This is a really nice package. I am following your quantile normalization tutorials and wanted to see how the normalization algorithm also adjusted the control probe values (i.e. extension, hybe, stain, etc...) Is there anyway I can view these values. I've only been able to access the raw values.

Cheers!

**Comment by perishky** [comment]
Sorry about the wait. I haven't been monitoring this very closely recently. 

The control probe values are not actually normalized, they are simply used to identify technical variation that should be removed from the DNA methylation probes.
