### ISSUE TITLE
Downloading of normalized Methylation values in simple .txt format

### ISSUE THREAD

**Issue by CornelisB** [perishky/meffil#29]
Is it also possible to download the normalized methylation values in simple .txt format for another program to use? eg methqtl standalone package?

Thanks

**Comment by perishky** [comment]
Certainly. After generating a normalized methylation matrix using meffil.normalize.samples() or meffil.normalize.dataset(): 

  e.g. meth <- meffil.normalize.samples(norm.objects)

you could then save that matrix as a text file as follows:

  write.table(meth, file="meth.txt", col.names=NA)

Depending on which program you plan to use, you might need to set other parameters in write.table() to get the output that the the program is expecting.

**Comment by CornelisB** [comment]
Very nice thanks a lot! 
Any ideas on representing the intensity data with chromosome and genes tracks?
Have two groups and would like to have a track for each group vs genes etc.

**Comment by perishky** [comment]
I've just added a function that I use for generating tracks for EWAS: meffil.ewas.bedgraph()
It may not produce exactly the output you want, but it shows how tracks can be constructed.

**Comment by perishky** [comment]
My colleague Josine Min suggested this package as well:
https://www.bioconductor.org/packages/release/bioc/html/coMET.html
