### ISSUE TITLE
Report variance of normalized betas principal components

### ISSUE THREAD

**Issue by yocra3** [perishky/meffil#32]
I am using meffil to normalize my dataset. In order to assess the potential effects of different batch variables on the final normalized beta values, the package offers an automated report which shows the associations between the user batch variables and the principal components of the normalized beta values.

Although this approach is great and has helped me a lot to identify potential issues, I am missing information about the variability explained by these principal components. If I am not wrong, this information is only provided for the control probes, but not for the normalized beta. 

I am aware that PCs are typically computed using the most variable CpGs and not the full dataset. However, even if the variability estimate does not fully reflect the total dataset variability, they can be helpful to determine which PCs are more relevant when trying to remove batch effects.

Thanks,

**Comment by perishky** [comment]
I think I've added what you are asking for: R^2 for each PC/batch variable association.  These will appear in the associations tables in the normalization report.  Let me know if that works for you.

**Comment by yocra3** [comment]
Hi @perishky,

I think that you did not understand me. In the new version of the report, the R2 measures how correlated is a batch variable with a principal component. Although this is very interesting and might be a good improvement, this is not what I needed.

I am interested in knowing how much variance explains each of the principal components. My goal is to decide which principal components I will take into consideration when evaluating the batch variables. For instance, if the first two components explain around 90% of variance, I probable won't look at the 3rd PC. However, if the first two components explain up to 30% of variance, I will probable care about the 3rd or 4th first PCs. 

If I am not wrong, I think that this info is available for the PCs of control probes and for the Meth and Unmeth signals. I am wondering if it would be possible to add this information in the normalization report.

**Comment by perishky** [comment]
Sorry about the misunderstanding.  You can calculate this directly using the principal components calculated for the normalization summary.  To create the summary, you would have already run this:
   pcs <- meffil.methylation.pcs(meth)
You could then determine the proportion of variance explained for each of the pcs as follows:
  v <- apply(pcs, 2, var)
  v/sum(v)

**Comment by yocra3** [comment]
Good morning,

I have just taken a look at the function `meffil.methylation.pcs` which computes the PC components of the methylation. I have realized that the last line is a call to base R `prcomp`, which performs the PCA computation:

```
prcomp(t(meffil:::impute.matrix(mat, margin = 1)))$x
```
In the current implementation, only the matrix with the PCAs is returned. Could you add a parameter to allow returning the full `prcomp` object? In this case, we will have available the PCA matrix, as well as the variance explained by each component. I can easily create a PR to make the change.

Bests,

**Comment by perishky** [comment]
I've added an argument 'full.obj' which is false by default.  If you set it to true, the function will return the full object. I haven't tested the change, do let me know how it goes.
