### ISSUE TITLE
cord blood gse68456

### ISSUE THREAD

**Issue by noriko01** [perishky/meffil#4]
Dear developer
Thank you for your great work. I'm having problems using cell type reference of "cord blood gse68456". Cell type "nRBC" is not defined, but "CD3T" is included, instead. I appreciate if you could kindly make an amendment.
Thank you in advance.

**Comment by perishky** [comment]
Thank you for checking on this noriko01.  It should be fixed now.  If not, please do let us know.

**Comment by noriko01** [comment]
Dear Author
Thank you so much*:)
noriko01

----- Original Message -----
