### ISSUE TITLE
Length > 1 error on R 4.2

### ISSUE THREAD

**Issue by hhp94** [perishky/meffil#40]
Dear Dr. Suderman, 

Thank you for your hard work on {meffil}. I'm using R 4.2, Windows build, {meffil} version 1.3.2 and I have the following error

```
library(meffil)
options(mc.cores = 6L)
my_scree_plot = meffil.plot.pc.fit(qc.object)
```

Which returned the error

```
Error in if (class(pca.ret) != "matrix") pca.ret <- pca.ret$x : 
  the condition has length > 1
```

I think this has to do with R 4.2 making length > 1 in if statement an error. I tried to look for the function that made this call but I couldn't find it. Can you help me?

Thank you so much

**Comment by epzjlm** [comment]
Hi,
Have you tried
`my_scree_plot <- meffil.plot.pc.fit(qc.objects)`

**Comment by hhp94** [comment]
Hi epzjm,

I just tried your suggestion and it didn't work. I think this is from R 4.2 making if statements with condition length > 1 an error rather than the assignment function.

A quick workaround for me for the moment would be to find the function that is making the `(class(pca.ret) != "matrix") pca.ret <- pca.ret$x` call and modify it e.g. `all(class(pca.ret) != "matrix")` or `class(pca.ret)[[1]] != "matrix"` or something.

**Comment by epzjlm** [comment]
It is in here: https://github.com/perishky/meffil/blob/master/R/design-matrix.r on line 152

**Comment by perishky** [comment]
Thanks for letting me know about this and diagnosing the problem! Should be fixed now.  Have changed the condition to 
! "matrix" %in% class(pca.ret)
