### ISSUE TITLE
DMPs vs DMRs

### ISSUE THREAD

**Issue by neuromik** [perishky/meffil#43]
Looks like EWAS function gives DMPs as an outcome. Is it possible to do DMR analysis? I've read in some studies that DMRs is a better way to compare methylation pattern.

Thanks!

**Comment by perishky** [comment]
Although meffil doesn't implement any DMR methods, DMR analyses are possible using a variety of different methods using meffil output, either EWAS summary statistics (e.g. a method we designed and implemented https://github.com/perishky/dmrff) or normalised data (e.g. https://github.com/timpeters82/DMRcate-release or https://github.com/raivokolde/seqlm).
