### ISSUE TITLE
meffil.ewas.summary with GDS

### ISSUE THREAD

**Issue by feichel** [perishky/meffil#47]
Hi!

Using a GDS file for meffil.ewas.summary does not seem to work:

```
Error in meffil::meffil.ewas.summary(ewas.object = res, beta = gds.filename,  : 
  is.matrix(beta) is not TRUE
```

All other functions that used this GDS file worked, so any clue, if this is on my end?

Thanks!

**Comment by perishky** [comment]
You did indeed uncover a bug in the code. Thank you!  It should be fixed now.

**Comment by feichel** [comment]
Thank you for fixing it! It works now.
