### ISSUE TITLE
More flexibility for Sex column

### ISSUE THREAD

**Issue by jlevy44** [perishky/meffil#7]
Hey there. I have been trying to import my csv file, but I keep getting this error:

Error in check.samplesheet(df) : 
  Sex column must only contain 'M', 'F' or NA values

I believe that this lies in how I set up my sex column. I feel that anything not explicitly 'M' or 'F' should be converted to NA before proceeding. I believe it's just having trouble recognizing blank values when reading in the csv.

If you could add na.strings=c("NA","NaN", " ") to read.csv line that would be great, or modify any(! samplesheet$Sex %in% c("M", "F", NA)) to include c("NA","NaN", " ").

Thanks!

**Comment by jlevy44** [comment]
I was able to get it to work, just thinking it might be easier to have that column be a little more flexible in what it can accept.

**Comment by perishky** [comment]
I've made the change you recommended.  Hopefully that does the trick.

**Comment by jlevy44** [comment]
Thanks. I'll give it a try.
